spring:
  datasource:
    url: jdbc:h2:mem:car-db
    username: user
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  graphql:
    schema:
      introspection:
        enabled: true
    graphiql:
      enabled: true
      path: /graphiql

logging:
  level:
    org.springframework.graphql: DEBUG